### PR TITLE
Documentation fix and demo site

### PR DESCRIPTION
**Pull request by aaronzshey**
Making a pull request to hold future commits.  I'll specify changes in the comments.

### CODE REVIEW

**Comment by Remeic** [comment]
Hi @CarlyRaeJepsenStan, thanks again for all!
I'm check you PR, seems that tests are broken, maybe is not related with your changes, anyway want to try to fix them?

` Requires Babel "^7.0.0-0", but was loaded with "6.26.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/giulio/Documents/Personale/vue-highlighter/node_modules/@babel/preset-env/lib/index.js"`

Feel free to open a new PR, if you solve it!

**Comment by aaronzshey** [comment]
@Remeic 🤔 I got a 404 issue on the codesandbox... I am updating the PR right now!

**Comment by aaronzshey** [comment]
@Remeic what's the status on this PR?

**Comment by Remeic** [comment]
> @Remeic what's the status on this PR?

Hi, i have a lot of work at my job, i will delay to review the PR

**Comment by aaronzshey** [comment]
Cool, thanks for letting me know.

**Pull request closed without merging**
